version: '3.8'
services:
  app:
    build: ./
    ports:
      - "3000:${PORT}"
    command: node app.js
    environment:
      NODE_ENV: "${NODE_ENV}"
      PORT: "${PORT}"
    volumes:
      - ./:/app
    depends_on:
      - db
    links:
      - db:mysql
  db:
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    driver: local
